Repository githiago-f/digital-wallet, pull requests merged in 2020-08, with the labels that each got.

#1 feat: adding icons
  src/assets/images/icons/activity.svg
  src/assets/images/icons/bell.svg
  src/assets/images/icons/config.svg
  src/assets/images/icons/dashboard.svg
  src/assets/images/icons/exchange.svg
  src/assets/images/icons/tools.svg
  src/assets/images/icons/wallets.svg
  src/assets/images/index.ts
Labels: enhancement

#2 feat: adding colors and themes
  src/components/StyleBase/index.tsx
Labels: enhancement

#4 feat: adding chart.js into project
  package.json
  yarn.lock
Labels: documentation, enhancement

#13 fix: typing correction
  tsconfig.json
Labels: bug

#14 feat: global @types structure
  .gitattributes
  src/@types/EnumCurrency.d.ts
  src/@types/card.d.ts
  src/@types/conversor.d.ts
  src/@types/props.base.d.ts
  src/@types/wallet.d.ts
  src/app/App.tsx
  src/components/Card/index.tsx
  src/components/Card/styles.tsx
  tsconfig.json
Labels: enhancement

#15 fix: typings and feat: current version of testing-library
  .eslintignore
  .eslintrc.yml
  .github/workflows/cicd.yml
  package.json
  src/__test__/placeholder.test.ts
  src/__test__/placeholder.test.tsx
  tsconfig.json
  yarn.lock
Labels: High level importance, enhancement
